### ISSUE TITLE
Dosn't work anymore

### ISSUE THREAD

**Issue by meenphie** [BefuddledLabs/LinuxVRChatSDKPatch#2]
The patch seems to be broken with the latest SDK 3.8.2

> HarmonyLib.HarmonyException: Patching exception in method null ---> System.ArgumentException: Undefined target method for patch method static System.Boolean BefuddledLabs.LinuxVRChatSdkPatch.Worlds.Editor.World::RunWorldTestDesktopPrefix(System.Object[] __args)
  at HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal, System.Boolean unpatch) [0x00047] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x0006e] in <abec11463bc04855a5322a0a868aeb22>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x00154] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x000a0] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) [0x00007] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <abec11463bc04855a5322a0a868aeb22>:0 
  at HarmonyLib.Harmony.PatchAll () [0x0001d] in <abec11463bc04855a5322a0a868aeb22>:0 
  at BefuddledLabs.LinuxVRChatSdkPatch.Worlds.Editor.Patch..cctor () [0x0001c] in ./Packages/befuddledlabs.linuxvrchatsdkpatch-worlds/Editor/Patch.cs:19

**Comment by DeltaNeverUsed** [comment]
Heya, Thanks for the bug report!
I should have a fix up in a couple of minutes

**Comment by DeltaNeverUsed** [comment]
Release 0.2.0 should fix this. Feel free to reopen if there are any other issues.

**Comment by meenphie** [comment]
Well, it's working but still not perfect. It takes like 5 minutes to launch VRChat client for some reason. Before it launched the VRC Client as soon as the build finished.

**Comment by DeltaNeverUsed** [comment]
hmm, that's strange, that wasn't happening on my end?
Could you check if this also happens in an empty project?

**Comment by meenphie** [comment]
A new project couldn't help, but I ended by deleting the proton prefix and now its working fine again.

**Comment by DeltaNeverUsed** [comment]
Strange, but I guess it wasn't an issue with the patch then?
